### ISSUE TITLE
Twig_Extension deprecated

### ISSUE THREAD

**Issue by vidurb** [EdwinHoksberg/octicons-php#4]
Hi Edwin,

Just wanted to let you know of the following deprecation message:
`Using the "Twig_Extension" class is deprecated since Twig version 2.7, use "Twig\Extension\AbstractExtension" instead.`

I'd be happy to submit a PR for the same, just let know.

**Comment by EdwinHoksberg** [comment]
Thanks for your report, it would be great if you could create a PR for it! 😄

**Comment by vidurb** [comment]
Please see #5 :smile_cat:

**Comment by EdwinHoksberg** [comment]
Closed by #5
